services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pm2-runtime ./config/ecosystem.config.js --env development
    ports:
      - 8001:8001
      - 8090:8090
  websocket:
    build:
      context: ./websocket-server
    ports:
      - "8080:8080"
    restart: always