name: Snyk scan of code

on:
  # push:
  #   branches: [ "uat" ]
  #   paths:
  #   - backend/**
  workflow_dispatch:

jobs:
  security-FE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            sparse-checkout: 'frontend'
            sparse-checkout-cone-mode: false

      - name: Move files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv frontend/* .
          rm -rf frontend
          ls -lah

      - name: Run Snyk to check for vulnerabilities (SCA)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: test

      - name: Run Snyk to check for vulnerabilities (SAST)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: code test

  security-BE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            sparse-checkout: 'backend'
            sparse-checkout-cone-mode: false

      - name: Move files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv backend/* .
          rm -rf backend
          ls -lah

      - name: Run Snyk to check for vulnerabilities (SCA)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: test

      - name: Run Snyk to check for vulnerabilities (SAST)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: code test

