name: Webrtc-server -- Build and deploy container to an Azure Web App

env:
  IMAGE_NAME: "webrtc-server-uat"
  AZ_REGISTRY: "phpcontainerregistry.azurecr.io"
  AZURE_WEBAPP_NAME: pethealthplatform-webrtc-uat

on:
  push:
    branches: [ "uat" ]
    paths:
    - webrtc-server/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  az-registry:
    name: Publish | Azure Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZ_REGISTRY }}
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.AZ_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags:
              type=raw,value=latest
          
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./webrtc-server
          file: ./webrtc-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: az-registry
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_SP_WEBRTC_UAT }}

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          images: ${{ env.AZ_REGISTRY }}/${{ env.IMAGE_NAME }}
